name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 * * * *" #Runs every hour
  
  workflow_dispatch: # Run workflow 
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: MoRevolution/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: d9163a59a20c6642e059d854bee6ae04
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
